python kmeans-fixK.py --dataset balance.txt
python kmeans-fixK.py --dataset bupa.txt
python kmeans-fixK.py --dataset haberman.txt
python kmeans-fixK.py --dataset hayes-roth.txt
python kmeans-fixK.py --dataset iris.txt
python kmeans-fixK.py --dataset monk-2.txt
python kmeans-fixK.py --dataset tae.txt
python kmeans-fixK.py --dataset yeast.txt
python kmeans-fixK.py --dataset glass.txt
python kmeans-fixK.py --dataset ecoli.txt
python kmeans-fixK.py --dataset wdbc.txt
python kmeans-fixK.py --dataset wine.txt
python kmeans-fixK.py --dataset appendicitis.txt
python kmeans-fixK.py --dataset contraceptive.txt
python kmeans-fixK.py --dataset heart.txt
python kmeans-fixK.py --dataset led7digit.txt
python kmeans-fixK.py --dataset pima.txt
python kmeans-fixK.py --dataset vehicle.txt
python kmeans-fixK.py --dataset winequality-red.txt
python kmeans-fixK.py --dataset zoo.txt
python kmeans-fixK.py --dataset seeds.txt
python kmeans-fixK.py --dataset vowel.txt
python kmeans-fixK.py --dataset australian.txt
python kmeans-fixK.py --dataset ionosphere.txt
python kmeans-fixK.py --dataset spectfheart.txt 
python kmeans-fixK.py --dataset movement_libras.txt
python kmeans-fixK.py --dataset sonar.txt 
python kmeans-fixK.py --dataset newthyroid.txt 

python kmeans-fixK.py --dataset dataR2.txt
python kmeans-fixK.py --dataset divorce.txt
python kmeans-fixK.py --dataset fertility_Diagnosis.txt
python kmeans-fixK.py --dataset lenses.data
python kmeans-fixK.py --dataset lymphography.txt
python kmeans-fixK.py --dataset SPECT.txt
python kmeans-fixK.py --dataset SPECTF.txt
python kmeans-fixK.py --dataset userknow.txt

python kmeans-fixK.py --dataset titanic.txt
python kmeans-fixK.py --dataset breastTissue.txt
python kmeans-fixK.py --dataset digits.txt 
python kmeans-fixK.py --dataset face.txt 
python kmeans-fixK.py --dataset musk1.txt