python open-set.py --dataset ecoli.txt
python open-set.py --dataset led7digit.txt
python open-set.py --dataset zoo.txt
python open-set.py --dataset digits.txt 
python open-set.py --dataset divorce.txt
python open-set.py --dataset fertility_Diagnosis.txt
python open-set.py --dataset lenses.data
python open-set.py --dataset breastTissue.txt
python open-set.py --dataset Spiral.tsv
python open-set.py --dataset skewed.txt
