python DOS-SN.py --dataset breastTissue.txt
python DOS-SN.py --dataset digits.txt
python DOS-SN.py --dataset divorce.txt
python DOS-SN.py --dataset ecoli.txt
python DOS-SN.py --dataset fertility_Diagnosis.txt
python DOS-SN.py --dataset led7digit.txt
python DOS-SN.py --dataset lenses.data
python DOS-SN.py --dataset zoo.txt
python DOS-SN.py --dataset skewed.txt
python DOS-SN.py --dataset Spiral.tsv
