python py_main.py --dataset divorce.txt
python py_main.py --dataset fertility_Diagnosis.txt
python py_main.py --dataset lenses.data
python py_main.py --dataset led7digit.txt
python py_main.py --dataset breastTissue.txt
python py_main.py --dataset digits.txt 
python py_main.py --dataset zoo.txt
python py_main.py --dataset ecoli.txt
python py_main.py --dataset Spiral.tsv
python py_main.py --dataset skewed.txt